Styling
emmanuellekamwa/bookstores pull request #4
Opened 2021-10-14 18:28 UTC by emmanuellekamwa

In this project I have: 
- Opened the project Bookstore CMS
- Used the information detailed in Zeplin to style the website

2021-10-14 18:47 UTC, e71az requested changes
## Status:  Invalid 🔴 

Hi, @emmanuellekamwa, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has linter errors, please fix them before requesting another review, have a nice day, and good luck!

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2021-10-15 07:48 UTC, Davidosky007 requested changes
## Hi @emmanuellekamwa 👋, 

Good job so far! 💪 
* Descriptive commit messages ✔️ 
* Proper git-flow pattern ✔️ 
* No linter errors ✔️ 
* Well written PR ✔️ 
* Professional readme file ✔️ 
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-15 07:48 UTC, Davidosky007 commented on src/redux/books/books.js
>  const initialState = [];
* I get an error in the console when i run `npm start` kindly fix this error.  HINT 💭: 
*  If you look at the console error message you will see that you are trying to import `redux/books/books.js` as `redux/books/Books.js` the `Books.js` in uppercase is the problem 😢 you can correct this by using the right file name 👍 
![image](https://user-images.githubusercontent.com/52497246/137450505-7b67a727-066a-49e3-9413-bca5e620baac.png)

2021-10-15 09:13 UTC, EricMbouwe approved these changes
### Hi @emmanuellekamwa, 

# Status: Approved ✔️
Excellent job on this project. Keep it up 👏
Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-15 09:13 UTC, merged